### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by Kovania** [jamsch/youtube-sync#1]
Hello !

I can not start the application.
I do a `npm install` and `node app.js` but it does not work.
So, how to launch this?

**Comment by jamsch** [comment]
Hey, to run the server you'll need to do the following:

1. run `npm install` to install the project's dependencies
2. Install socket.io - `npm install -S socket-io`. there's probably other dependencies that I left out of the package dependencies
3. `npm start` or `node ./bin/www` to start the server on port 3000. It probably won't notify you that the server started running

Keep in mind this is an old and incomplete project that I started when learning node.js & JavaScript in general. Some dependencies like Jade have rebranded to [Pug](https://github.com/pugjs/pug) so I'm not sure if that package is even available on npm anymore.
